### ISSUE TITLE
Not working stock management example on colab

### ISSUE THREAD

**Issue by farzaneh-mahmoudi** [t-wolfeadam/Alpyne#36] opened 2023-01-20 13:39 UTC
Hello wolfeadam,
I watched the video of the stock management example and I really enjoyed that. I wanted to test and run "[rlpolicy_train.py](https://github.com/t-wolfeadam/Alpyne/blob/main/examples/Stock%20Management%20Game/rlpolicy_train.py)" without any editing on google Colab and it was not working.
The screenshot of the error and alpyne.log and screenshots of execution has attached.
As I am a junior in coding and RL, I don't understand the exact problem, I would appreciate your help.
Thank you
![code error](https://user-images.githubusercontent.com/64431346/213708015-ffb7aaa0-06b8-46b1-847c-3633b4bdecd5.PNG)
![execution 1](https://user-images.githubusercontent.com/64431346/213708029-bf756ad9-0744-48fd-a742-a4c481c3148b.PNG)
![execution 2](https://user-images.githubusercontent.com/64431346/213708033-c9fd8499-dda7-48cc-8492-5943ae089614.PNG)
[alpyne.log](https://github.com/t-wolfeadam/Alpyne/files/10466733/alpyne.log)

**Comment by t-wolfeadam** [comment] 2024-03-16 01:01
Likely a duplicate of #10, which I'm keeping open until I check whether it works there in v1.0.0. Feel free to try this too and, if you do, report on that issue there

**Closed by t-wolfeadam** 2024-03-16 01:01 UTC

**Comment by t-wolfeadam** [comment] 2024-03-16 01:05
This may be resolved in v1.0.0. I suggest upgrading and trying, and feel free to open a new issue if it remains.
